### ISSUE TITLE
Python version constraint

### ISSUE THREAD

**Issue by condekind** [pronesto/DCC888#4]
I (think I) remember an earlier version of README stating the Python version was limited to 3.9 due to the labs being evaluated by Moodle. Is that still true? If so, I suggest adding a file `.python-version` at the root of the repo with the content:
```
3.9.18
```
(this creation can also be done with `pyenv local 3.9.18`)

This file is used by [pyenv](https://github.com/pyenv/pyenv?tab=readme-ov-file#what-pyenv-does), which many people use to manage their locally installed python versions. I can open a PR with the change if there's agreement on this.

> **Note**: It doesn't interfere with people that don't use pyenv

Users with pyenv would need to `pyenv install 3.9.18`. Then, with the simple existence of this file (assuming pyenv was correctly set up in the shell), the python version inside the project (and all subdirectories) should resolve to `3.9.18`. To verify it, run: `python --version` after the above (it works even without a virtualenv).

I'd still recommend¹ running `python -m venv .venv` from the root of the repo _after the above is done and verified_, but that's just an extra layer of env isolation, in case 3.9.18 is used by other projects.

¹: __If__ a `.venv` is created, it needs to be activated with `source .venv/bin/activate`. This has to be executed for every shell ("terminal"). That includes the one that created it, as well as new ones. Note: some IDEs can be configured to activate a virtualenv automatically when opening terminals (PyCharm is one).

**Comment by condekind** [comment]
Note: I'm hoping the restriction no longer exists so we can use the cool features of newer versions - however, the concern about agreeing on a specific version remains valid. For reference, the newest stable version one can install with pyenv is `3.12.2`

**Comment by pronesto** [comment]
Hi Bruno! The current version is still 3.9. I've added the 3.9.18 version to the `.python-version` file.
